{{- if .Values.webhooks.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pdb-operator.fullname" . }}-mutating
  labels:
    {{- include "pdb-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pdb-operator.fullname" . }}-serving-cert
  {{- end }}
webhooks:
  - name: mpdbpolicy-v1alpha1.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "pdb-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-availability-pdboperator-io-v1alpha1-pdbpolicy
    failurePolicy: {{ .Values.webhooks.failurePolicy }}
    timeoutSeconds: {{ .Values.webhooks.timeoutSeconds }}
    rules:
      - apiGroups:
          - availability.pdboperator.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pdbpolicies
    sideEffects: None
{{- end }}
