{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdb-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdb-operator.labels" . | nindent 4 }}
  {{- with .Values.webhooks.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.webhooks.port }}
      targetPort: {{ .Values.webhooks.targetPort }}
      protocol: TCP
  selector:
    {{- include "pdb-operator.selectorLabels" . | nindent 4 }}
{{- end }}
